server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jdbc?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

mybatis:
  #该配置表示sql xml文件存放的地址
  mapper-locations: classpath:*.xml
  type-aliases-package: com.yjs.yujiangshe.po